apiVersion: database.example.com/v1alpha1
kind: DatabaseBackup
metadata:
  labels:
    app.kubernetes.io/name: database-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasebackup-sample
spec:
  # TODO(user): Add fields here
