apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-label-controller-role-binding
subjects:
- kind: ServiceAccount
  name: default   
  namespace: default   
roleRef:
  kind: ClusterRole
  name: pod-label-controller-role 
  apiGroup: rbac.authorization.k8s.io
