apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  annotations:
    auto-label: "true"  # custom controller will react to this annotation
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
